// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VpnDashboard.Data;

#nullable disable

namespace VpnDashboard.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("VpnDashboard.Data.Entities.GlobalSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GlobalSubscriptions");
                });

            modelBuilder.Entity("VpnDashboard.Data.Entities.HiddifyServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminProxyPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientProxyPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPingAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HiddifyServers");
                });

            modelBuilder.Entity("VpnDashboard.Data.Entities.LocalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShowcaseToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShowcaseToken")
                        .IsUnique();

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("VpnDashboard.Data.Entities.ManualSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalUserId");

                    b.ToTable("ManualSubscriptions");
                });

            modelBuilder.Entity("VpnDashboard.Data.Entities.UserGlobalSubscription", b =>
                {
                    b.Property<Guid>("LocalUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GlobalSubscriptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("LocalUserId", "GlobalSubscriptionId");

                    b.HasIndex("GlobalSubscriptionId");

                    b.ToTable("UserGlobalSubscriptions");
                });

            modelBuilder.Entity("VpnDashboard.Data.Entities.UserServerBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HiddifyServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HiddifyUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBroken")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LocalUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HiddifyServerId");

                    b.HasIndex("LocalUserId", "HiddifyServerId")
                        .IsUnique();

                    b.ToTable("UserServerBindings");
                });

            modelBuilder.Entity("VpnDashboard.Data.Entities.ManualSubscription", b =>
                {
                    b.HasOne("VpnDashboard.Data.Entities.LocalUser", "LocalUser")
                        .WithMany("ManualSubscriptions")
                        .HasForeignKey("LocalUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalUser");
                });

            modelBuilder.Entity("VpnDashboard.Data.Entities.UserGlobalSubscription", b =>
                {
                    b.HasOne("VpnDashboard.Data.Entities.GlobalSubscription", "GlobalSubscription")
                        .WithMany("Assignments")
                        .HasForeignKey("GlobalSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VpnDashboard.Data.Entities.LocalUser", "LocalUser")
                        .WithMany("GlobalSubscriptions")
                        .HasForeignKey("LocalUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalSubscription");

                    b.Navigation("LocalUser");
                });

            modelBuilder.Entity("VpnDashboard.Data.Entities.UserServerBinding", b =>
                {
                    b.HasOne("VpnDashboard.Data.Entities.HiddifyServer", "HiddifyServer")
                        .WithMany("Bindings")
                        .HasForeignKey("HiddifyServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VpnDashboard.Data.Entities.LocalUser", "LocalUser")
                        .WithMany("Bindings")
                        .HasForeignKey("LocalUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HiddifyServer");

                    b.Navigation("LocalUser");
                });

            modelBuilder.Entity("VpnDashboard.Data.Entities.GlobalSubscription", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("VpnDashboard.Data.Entities.HiddifyServer", b =>
                {
                    b.Navigation("Bindings");
                });

            modelBuilder.Entity("VpnDashboard.Data.Entities.LocalUser", b =>
                {
                    b.Navigation("Bindings");

                    b.Navigation("GlobalSubscriptions");

                    b.Navigation("ManualSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
